package database

import (
	"context"
	"database/sql"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/phpmyadmin/phpmyadmin/backend/internal/models"
)

type ExportFormat string

const (
	FormatSQL   ExportFormat = "sql"
	FormatCSV   ExportFormat = "csv"
	FormatJSON  ExportFormat = "json"
	FormatXML   ExportFormat = "xml"
)

func ExportTable(ctx context.Context, db *sql.DB, dbName, tableName string, format ExportFormat) (string, error) {
	columns, err := GetColumns(ctx, db, dbName, tableName)
	if err != nil {
		return "", fmt.Errorf("failed to get columns: %w", err)
	}

	rows, err := db.QueryContext(ctx, fmt.Sprintf("SELECT * FROM `%s`.`%s`", dbName, tableName))
	if err != nil {
		return "", fmt.Errorf("failed to query data: %w", err)
	}
	defer rows.Close()

	switch format {
	case FormatSQL:
		return exportToSQL(ctx, db, dbName, tableName, columns, rows)
	case FormatCSV:
		return exportToCSV(columns, rows)
	case FormatJSON:
		return exportToJSON(columns, rows)
	case FormatXML:
		return exportToXML(dbName, tableName, columns, rows)
	default:
		return "", fmt.Errorf("unsupported format: %s", format)
	}
}

func exportToSQL(ctx context.Context, db *sql.DB, dbName, tableName string, columns []models.ColumnInfo, rows *sql.Rows) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("-- Database: %s\n", dbName))
	sb.WriteString(fmt.Sprintf("-- Table: %s\n", tableName))
	sb.WriteString(fmt.Sprintf("-- Generated by phpMyAdmin Go\n\n"))

	sb.WriteString(fmt.Sprintf("DROP TABLE IF EXISTS `%s`;\n", tableName))

	createTableQuery := ""
	row := db.QueryRowContext(ctx, fmt.Sprintf("SHOW CREATE TABLE `%s`.`%s`", dbName, tableName))
	var tableNameOut, createSQL string
	if err := row.Scan(&tableNameOut, &createSQL); err == nil {
		createTableQuery = createSQL
		sb.WriteString(createTableQuery)
		sb.WriteString(";\n\n")
	}

	values := make([]interface{}, len(columns))
	valuePtrs := make([]interface{}, len(columns))
	for i := range columns {
		valuePtrs[i] = &values[i]
	}

	for rows.Next() {
		if err := rows.Scan(valuePtrs...); err != nil {
			return "", fmt.Errorf("failed to scan row: %w", err)
		}

		sb.WriteString(fmt.Sprintf("INSERT INTO `%s` (", tableName))
		for i, col := range columns {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("`%s`", col.Field))
		}
		sb.WriteString(") VALUES (")

		for i, val := range values {
			if i > 0 {
				sb.WriteString(", ")
			}
			if val == nil {
				sb.WriteString("NULL")
			} else {
				sb.WriteString(fmt.Sprintf("'%v'", strings.Replace(fmt.Sprintf("%v", val), "'", "\\'", -1)))
			}
		}
		sb.WriteString(");\n")
	}

	return sb.String(), nil
}

func exportToCSV(columns []models.ColumnInfo, rows *sql.Rows) (string, error) {
	var sb strings.Builder
	writer := csv.NewWriter(&sb)

	headers := make([]string, len(columns))
	for i, col := range columns {
		headers[i] = col.Field
	}
	if err := writer.Write(headers); err != nil {
		return "", fmt.Errorf("failed to write headers: %w", err)
	}

	values := make([]interface{}, len(columns))
	valuePtrs := make([]interface{}, len(columns))
	for i := range columns {
		valuePtrs[i] = &values[i]
	}

	for rows.Next() {
		if err := rows.Scan(valuePtrs...); err != nil {
			return "", fmt.Errorf("failed to scan row: %w", err)
		}

		record := make([]string, len(columns))
		for i, val := range values {
			if val == nil {
				record[i] = ""
			} else {
				record[i] = fmt.Sprintf("%v", val)
			}
		}
		if err := writer.Write(record); err != nil {
			return "", fmt.Errorf("failed to write record: %w", err)
		}
	}

	writer.Flush()
	if err := writer.Error(); err != nil {
		return "", fmt.Errorf("csv writer error: %w", err)
	}

	return sb.String(), nil
}

func exportToJSON(columns []models.ColumnInfo, rows *sql.Rows) (string, error) {
	var data []map[string]interface{}

	values := make([]interface{}, len(columns))
	valuePtrs := make([]interface{}, len(columns))
	for i := range columns {
		valuePtrs[i] = &values[i]
	}

	for rows.Next() {
		if err := rows.Scan(valuePtrs...); err != nil {
			return "", fmt.Errorf("failed to scan row: %w", err)
		}

		row := make(map[string]interface{})
		for i, col := range columns {
			row[col.Field] = values[i]
		}
		data = append(data, row)
	}

	jsonData, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to marshal JSON: %w", err)
	}

	return string(jsonData), nil
}

func exportToXML(dbName, tableName string, columns []models.ColumnInfo, rows *sql.Rows) (string, error) {
	var sb strings.Builder

	sb.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	sb.WriteString(fmt.Sprintf("<database name=\"%s\">\n", dbName))
	sb.WriteString(fmt.Sprintf("  <table name=\"%s\">\n", tableName))

	values := make([]interface{}, len(columns))
	valuePtrs := make([]interface{}, len(columns))
	for i := range columns {
		valuePtrs[i] = &values[i]
	}

	for rows.Next() {
		if err := rows.Scan(valuePtrs...); err != nil {
			return "", fmt.Errorf("failed to scan row: %w", err)
		}

		sb.WriteString("    <row>\n")
		for i, col := range columns {
			val := values[i]
			if val == nil {
				sb.WriteString(fmt.Sprintf("      <field name=\"%s\" xsi:nil=\"true\"/>\n", col.Field))
			} else {
				escapedValue := strings.Replace(fmt.Sprintf("%v", val), "&", "&amp;", -1)
				escapedValue = strings.Replace(escapedValue, "<", "&lt;", -1)
				escapedValue = strings.Replace(escapedValue, ">", "&gt;", -1)
				escapedValue = strings.Replace(escapedValue, "\"", "&quot;", -1)
				sb.WriteString(fmt.Sprintf("      <field name=\"%s\">%s</field>\n", col.Field, escapedValue))
			}
		}
		sb.WriteString("    </row>\n")
	}

	sb.WriteString("  </table>\n")
	sb.WriteString("</database>\n")

	return sb.String(), nil
}

func ExportDatabase(ctx context.Context, db *sql.DB, dbName string, format ExportFormat) (string, error) {
	tables, err := GetTables(ctx, db, dbName)
	if err != nil {
		return "", fmt.Errorf("failed to get tables: %w", err)
	}

	if format == FormatSQL {
		return exportDatabaseToSQL(ctx, db, dbName, tables)
	}

	var sb strings.Builder
	for _, table := range tables {
		tableData, err := ExportTable(ctx, db, dbName, table.Name, format)
		if err != nil {
			return "", fmt.Errorf("failed to export table %s: %w", table.Name, err)
		}
		sb.WriteString(tableData)
		sb.WriteString("\n")
	}

	return sb.String(), nil
}

func exportDatabaseToSQL(ctx context.Context, db *sql.DB, dbName string, tables []models.TableInfo) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("-- Database: %s\n", dbName))
	sb.WriteString("-- Generated by phpMyAdmin Go\n\n")
	sb.WriteString(fmt.Sprintf("CREATE DATABASE IF NOT EXISTS `%s`;\n", dbName))
	sb.WriteString(fmt.Sprintf("USE `%s`;\n\n", dbName))

	for _, table := range tables {
		tableData, err := ExportTable(ctx, db, dbName, table.Name, FormatSQL)
		if err != nil {
			return "", fmt.Errorf("failed to export table %s: %w", table.Name, err)
		}
		sb.WriteString(tableData)
		sb.WriteString("\n")
	}

	return sb.String(), nil
}
